### ISSUE TITLE
JEA roles can't find modules in version folders

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/JEA#18]
Got this one from a customer at PS Summit NA 2017: 

If you use `Install-Module` to install a module, it gets placed in a folder that looks like `$env:PSModulePath\ModuleName\Version`. Apparently, when you try to join a session with a given JEA role, the session cannot find its allowed modules unless you move the module up out of the version folder (so from, e.g. `1.0.1.0` to `ModuleName`).

**Comment by jnury** [comment]
Hello @joeyaiello,
Hi opened this bug some time ago: https://github.com/PowerShell/PowerShell/issues/3522
Seems it's fixed in PS 6.

Personally, I create a junction when deploying the module (thru DSC):
`New-Item -ItemType Junction -Path _ModulePath_\myModule\RoleCapabilities -Target _ModulePath_\myModule\1.0.1.0\RoleCapabilities`

**Comment by rpsqrd** [comment]
Going to close this issue in response to the above and the JEA-specific issue that tracks this: [PowerShell/PowerShell#4104](https://github.com/PowerShell/PowerShell/issues/4104)
