### ISSUE TITLE
JEA and Select-Object in Visible Functions

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/JEA#26]
So, doing a live presentation with the St. Louis PowerShell usergroup, we ran into Select-Object malfunctioning in a JEA endpoint from our expectations.

We wrote a simple function to check for installed software in registry and return only display name and version, but errored out on the `Select-Object` call, exception below:

```
Cannot validate argument on parameter 'Property'. The argument "myArguments" does not belong to the set "ModuleName,Namespace,OutputType,Count,HelpUri,Name,CommandType,ResolvedCommandName,DefaultParameterSet,CmdletBinding,Parameters" specified by the
ValidateSet attribute.
```

We "solved" it by using the workaround [here](https://powershell.org/forums/topic/jea-restrictedremoteserver-and-select-object-unusable/).

Is this the expected behavior? 99% of all uses of `Select-Object` I see include specifying properties.

**Comment by rpsqrd** [comment]
Yes, this is the expected behavior for custom functions you define. While not entirely obvious, we do document it in our example on how to [create custom functions](https://docs.microsoft.com/en-us/powershell/jea/role-capabilities#creating-custom-functions) in a JEA role capability file.

Select-Object gets a default constrained parameter set when you set `SessionType = 'RestrictedRemoteServer'` in the session configuration file, and the resulting proxy function takes precedence over the built-in cmdlet definition for that session. The reason we constrain Select-Object by default is to prevent information leakage -- some users should not have access to inspect arbitrary properties of objects returned to the console. If this is not a concern for you, you can consider allowing the unconstrained Select-Object cmdlet in your role capability file, but we would typically recommend you stick to using fully qualified module names to refer to it in custom functions instead. Alternatively, you can put your functions in a script module file and grant users access to that module's commands. Select-Object in a module (vs. session) context will refer to the built-in, unconstrained cmdlet by default.

Hope this clears things up!

**Comment by michaeltlombardi** [comment]
> . Alternatively, you can put your functions in a script module file and grant users access to that module's commands. Select-Object in a module (vs. session) context will refer to the built-in, unconstrained cmdlet by default.

This is, unfortunately, what we were actually doing. We defined a function in a module, ensured that that module is imported and the specified command visible, and it errored out because it used the proxy command.

I definitely concede that the _better practice_ is to always fully qualify function/cmdlet calls, especially in modules intended to be used in JEA endpoints. 

Unfortunately, for most folks, that means rewriting 99% of the modules they may want to use in a JEA session. 

Our [work](https://gitlab.com/barbariankb/JEA) last night, for reference. The module is inside the `Source` folder.

**Comment by rpsqrd** [comment]
> Unfortunately, for most folks, that means rewriting 99% of the modules they may want to use in a JEA session.

Only true if they try putting them in the FunctionDefinitions field of a PSRC/PSSC. As long as they're in a proper module, there should not be any changes required.

For customers who already have scripts (not script modules) to do a task, they can just add the path to the script in VisibleExternalCommands. Then, in the JEA session, they just need to type the script name and any parameters. It won't allow them to constrain the parameters, but it avoids needing to rewrite code to onboard JEA.

Thanks for sharing your experiences with JEA -- it's always great to see the community rally around practical security tools.

**Comment by michaeltlombardi** [comment]
Sorry, I meant that we used `Select-Object` in a function, in a module, and got the same results as you're describing to be expected if we defined it in the PSRC/PSSC. It sounds like it _should not_ have been proxied in this case.

FQ command calls are probably a generic best practice for writing scripts/functions/modules for use in an environment where you're security conscious, but it's not _common_ practice yet.

**Comment by michaeltlombardi** [comment]
We had to edit [this line](https://gitlab.com/barbariankb/JEA/blob/master/source/BarbarianKB.JEA.psm1#L41), to use the alias of `Select-Object` to get around the proxy issue.

**Comment by rpsqrd** [comment]
@PaulHigin Am I mistaken here? Are Select-Object calls in a script module expected to use the native Select-Object or the constrained proxy function included in JEA configurations?

I thought the proxy function precedence was limited to those functions defined in a FunctionDefinitions field in a PSSC/PSRC, but it appears I may have misunderstood this behavior.

**Comment by PaulHigin** [comment]
No, the JEA proxy functions are defined in the session and take precedence over built-in commands they may replace.  To override them you need to use the fully qualified command name to specify the built-in command(Microsoft.PowerShell.Utility\Select-Object) as you discovered.  

It is great to see people using this.  Please let me know if I can answer anymore questions.

**Comment by michaeltlombardi** [comment]
So, just to clarify, it's the _expected behavior_ for the following:

I define the following module, `MyModule.psm1`:

```powershell
Function Get-Arbitrary {
  [cmdletbinding()]
  Param ()
  Get-ChildItem -Path C:\ | Select-Object -Property FullName
}
Export-ModuleMember -Function *
```

The following in the RoleCapabilities folder inside said module, as `Arbitrary.psrc`:

```powershell
@{
  GUID = '771ffcd2-4317-4c95-9a59-3d0dfbb94681'
  ModulesToImport = 'SomethingArbitrary'
  VisibleFunctions = 'SomethingArbitrary\Get-Arbitrary'
}
```

And this PSSC:

```powershell
@{
    SchemaVersion       = '2.0.0.0'
    GUID                = '15f514dc-4b9f-43f4-aa3b-8db467e969f9'
    SessionType         = 'RestrictedRemoteServer'
    ExecutionPolicy     = 'Unrestricted'
    TranscriptDirectory = 'C:\Transcripts\Arbitrary'
    RunAsVirtualAccount = $true
    RoleDefinitions     = @{
        "COMPANY\SomeGroup" = @{ RoleCapabilities = 'Arbitrary' }
    }
}
```

Then, when I enter the JEA endpoint using the configuration above and try to run `Get-Arbitrary`, it's _expected behavior_ for this to error out?

**Comment by michaeltlombardi** [comment]
If we want this to work, we should fully qualify the `Select-Object` call _inside our module_ which is deployed to the JEA endpoint, correct? Meaning all script modules relying on `Select-Object -Property` should expect to fail **unless** the call to `Select-Object` is fully qualified.

**Comment by PaulHigin** [comment]
Yes, in fact this is what our internal script does, it uses "Microsoft.PowerShell.Utility\Select-Object" in order to use the built-in command, because we know we are using it safely.

Keep in mind that these proxy functions are only created for SessionType == RestrictedRemoteServer because we need to guarantee the restricted session/commands are safe.  You can create your own endpoint session type that is less restrictive but we don't recommend it if you our concerned about security.  A lot of effort went into ensuring the RestrictedRemoteServer session type is secure.

Generally you don't want to just expose your custom module as-is in a secure JEA endpoint, because you could be exposing security vulnerabilities such as code injection or privilege elevation.  You should do a complete security review and ensure all commands/functions you are exposing are safe.

**Comment by michaeltlombardi** [comment]
> You should do a complete security review and ensure all commands/functions you are exposing are safe.

One hundred percent, loudly agree with this. I just didn't realize that non-fully-qualified function calls inside modules would use the proxy functions. I have no real problems with this behavior, just needed clarity - I suggest that this stumbling block indicates the docs are not explicit enough on this point.

I'll start ensuring all of _my_ function calls in modules are fully qualified, at least, and make sure to include this information when I talk about / evangelize JEA.
