### ISSUE TITLE
Tab Completion

### ISSUE THREAD

**Issue by jhack31** [PowerShell/JEA#8]
Is there a way to get tab completion working with JEA endpoints?

**Comment by austoonz** [comment]
Agreed - the whole idea of JEA to expose PowerShell functions to support staff almost requires tab completion to make this successful.

**Comment by alexaymonier** [comment]
Agree 3, thought i was doing something wrong till i stumbled over this.

**Comment by SteveL-MSFT** [comment]
The recommendation is to import-pssession and things like tab completion will work while not impacting the secure environment of the JEA endpoint

**Comment by jhack31** [comment]
Can you point us to some documentation on thiis?  Everything I've seen on this site indicates to use Enter-PSSession (not import-pssession).  When trying to import-pssession with my JEA session configuration, it shows me all commands for my local computer and the commands against the endpoint are failing.

**Comment by jhack31** [comment]
Import-PSSession -Session $myjeasession -AllowClobber did allow for tab completion with my JEA config.

**Comment by SteveL-MSFT** [comment]
@rpsqrd we should update the docs to discuss enter-pssession vs import-pssession.  The short version is that by-design many things are limited in the JEA endpoint to prevent breaking out of the sandbox.  Import-pssession is safe as things like tab-completion happen on the client side rather than the endpoint side so you can do full PowerShell scripting on the client and only when you take actions against cmdlets imported from the JEA session does JEA apply.

**Comment by rpsqrd** [comment]
Check out our new documentation for information on how to use JEA with implicit remoting. As @SteveL-MSFT said, this will give you the best of both worlds: unconstrained language on the client side and security on the server side.

https://msdn.microsoft.com/en-us/powershell/jea/using-jea#using-jea-with-implicit-remoting

**Comment by hector7869** [comment]
You can enable the TabExpansion2 function in the Role Definition to get this working. 

VisibleFunctions = 'TabExpansion2'
